### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabriel-maxx** [keowu/wintapix#2]
Hello, i compiled the driver and tested it on windows 7 x64 and windows 11 x64 and when i start the driver i got a blue screen with the error "SYSTEM THREAD EXCEPTION NOT HANDLED" both machines were with the test mode activated so I can load the driver, do you know how I solve this error?

**Comment by keowu** [comment]
Hello, thanks for report it, i will take a look soon.

**Comment by keowu** [comment]
Hi

Once again, thank you for your report; it is an important contribution to my project.

I have reviewed the code, and there is no issue with the code itself. The problem here is with the search for the System Service Descriptor Table, which was not designed for newer versions of the operating system. Please remember that this is a malware, so I do not intend to adapt or fix this issue by implementing a more effective search method (functional for newer versions of Windows NT), as the project is meant to mimic the malware's functionality and targets.

If you still wish to test the project, please follow these steps, no other steps is needed:

1. Have a VM with Microsoft Windows 10 1607 x64 (Get it here: https://archive.org/download/microsoft-windows-10-1607-oct-2016-64-bit).

2. After setting up the VM environment, simply disable kernel signature enforcement, and everything should be fine for testing the project, with no exceptions occurring.

**!** Please note that sometimes the debug viewer from Sysinternals may have issues on Windows 10 with debug outputs, so create a registry key: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter" Create a new key with the name "DEFAULT," with a DWORD (32-bit) type, and set the value to "0xFFFFFFFF".

Best regards,
Keowu

**Comment by gabriel-maxx** [comment]
> The problem here is with the search for the System Service Descriptor Table, which was not designed for newer versions of the operating system.
> 
But then what about Windows 7 shouldn't work? If I just want the shellcode injection part in processes without the persistence part, etc., what should I do to make it work on Windows 11? Sorry, I'm not very good at programming, I'm still learning...
